---
language: minimal
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.22.0
services:
  - docker
branches:
  only:
    - master
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in .env.enc -out .env -d
stages:
  - unit_tests
  - deploy
  - clean
jobs:
  include:
  - stage: unit_tests
    name: Unit Tests
    script:
      - make test
  - stage: deploy
    name: Deploy to Docker Hub
    script:
      - make deploy
  - stage: clean
    name: Clean up working env
    script:
      - make clean
