---
version: "2.4"
services:
  base:
    build:
      context: .
      dockerfile: base.Dockerfile
  unit-tests:
    extends: base
    environment:
      - DOCKER_IMAGE_UNDER_TEST
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_PWD?Please specify the app directory from the host.}:/app
    working_dir: /app
    command:
      - /app/tests
  push-to-docker-hub:
    extends: base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_PWD?Please specify the app directory from the host.}:/app
    env_file: .env
    entrypoint:
      - sh
      - "-c"
      - "docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD} && \
         docker tag ${DOCKER_IMAGE_TO_DEPLOY} ${TAG_TO_USE}:${GIT_SHA?Please provide a Git commit SHA} && \
         docker push ${TAG_TO_USE}:${GIT_SHA} && \
         docker tag ${DOCKER_IMAGE_TO_DEPLOY} ${TAG_TO_USE}:latest && \
         docker push ${TAG_TO_USE}:latest"
